GoFish.Web/Models/ErrorViewModel.cs
using System;

namespace GoFish.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GoFish.Web/Models/Forum/ForumDetailModel.cs
using GoFish.Web.Models.Post;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GoFish.Web.Models.Forum
{
    public class ForumDetailModel
    {
        public ForumListingModel Forum { get; set; }
        public IEnumerable<PostListingModel> Posts { get; set; }
    }
}

GoFish.Web/Models/Forum/ForumIndexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GoFish.Web.Models.Forum
{
    public class ForumIndexModel
    {
        public IEnumerable<ForumListingModel> ForumList { get; set; }
    }
}

GoFish.Web/Models/Forum/ForumListingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GoFish.Web.Models.Forum
{
    public class ForumListingModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
    }
}

GoFish.Web/Models/Post/PostIndexModel.cs
using GoFish.Web.Models.Reply;
using System;
using System.Collections.Generic;

namespace GoFish.Web.Models.Post
{
    public class PostIndexModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string AuthorId { get; set; }
        public string AuthorName { get; set; }

        public string AuthorImageUrl { get; set; }
        public int AuthorRating { get; set; }
        public DateTime Created { get; set; }
        public string PostContent { get; set; }

        public IEnumerable<PostReplyModel> Replies { get; set; }

    }
}

GoFish.Web/Models/Post/PostListingModel.cs
using GoFish.Web.Models.Forum;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GoFish.Web.Models.Post
{
    public class PostListingModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string AuthorName { get; set; }
        public int AuthorRating { get; set; }
        public string AuthorId { get; set; }
        public string DateCreated { get; set; }        

        public ForumListingModel Forum { get; set; }
        public int RepliesCount { get; set; }

    }
}

GoFish.Web/Models/Reply/PostReplyModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GoFish.Web.Models.Reply
{
    public class PostReplyModel
    {
        public int Id { get; set; }
        public string AuthorId { get; set; }
        public string AuthorName { get; set; }
        public int AuthorRating { get; set; }
        public string AuthorImageUrl { get; set; }
        public DateTime Created { get; set; }
        public string ReplyContent { get; set; }

        public int PostId { get; set; }

    }
}

GoFish.Web/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GoFish.Data;
using GoFish.Data.Models;
using GoFish.Web.Models.Forum;
using GoFish.Web.Models.Post;
using Microsoft.AspNetCore.Mvc;

namespace GoFish.Web.Controllers
{
    public class ForumController : Controller
    {
        private readonly IForum _forumService;
        private readonly IPost _postService;

        public ForumController(IForum forumService, IPost postService)
        {
            _forumService = forumService;
            _postService = postService;
        }

        public IActionResult Index()
        {
            var forums = _forumService.GetAll()
                .Select(f => new ForumListingModel
                {
                    Id = f.Id,
                    Title = f.Title,
                    Description = f.Description
                }
            ).OrderBy(f => f.Title);

            var model = new ForumIndexModel
            {
                ForumList = forums
            };

            return View(model);
        }

        public IActionResult Detail(int id)
        {
            var forum = _forumService.GetById(id);
            var posts = forum.Posts;

            var postListing = posts.Select(post => new PostListingModel
            { 
                Id = post.Id,
                AuthorId = post.User.Id,
                AuthorName = post.User.UserName,
                AuthorRating = post.User.Rating,
                Title = post.Title,
                DateCreated = post.Created.ToString(),
                RepliesCount = post.Replies.Count(),
                Forum = BuildForumListing(post)
            }).ToList();

            var model = new ForumDetailModel
            {
                Posts = postListing,
                Forum = BuildForumListing(forum)
            };
                
            return View(model);
        }

        private ForumListingModel BuildForumListing(Post post)
        {
            var forum = post.Forum;
            return BuildForumListing(forum);
        }

        private ForumListingModel BuildForumListing(Forum forum)
        {
            return new ForumListingModel
            {
                Id = forum.Id,
                Title = forum.Title,
                Description = forum.Description,
                ImageUrl = forum.ImageUrl
            };
        }
    }
}

GoFish.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GoFish.Web.Models;

namespace GoFish.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GoFish.Web/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GoFish.Data;
using GoFish.Data.Models;
using GoFish.Web.Models.Post;
using GoFish.Web.Models.Reply;
using Microsoft.AspNetCore.Mvc;

namespace GoFish.Web.Controllers
{
    public class PostController : Controller
    {
        private readonly IPost postService;

        public PostController(IPost postService)
        {
            this.postService = postService;
        }
        public IActionResult Index(int id)
        {
            var post = postService.GetById(id);

            var model = new PostIndexModel
            {
                Id = post.Id,
                Title = post.Title,
                AuthorId = post.User.Id,
                AuthorName = post.User.UserName,
                //AuthorImageUrl = post.User.ProfileImage,
                //AuthorRating= post.User.Rating,
                PostContent = post.Content,
                Created = post.Created,
                Replies = BuildPostReplies(post.Replies)
        };
            return View(model);
        }

        private IEnumerable<PostReplyModel> BuildPostReplies(IEnumerable<PostReply> replies)
        {
            return replies.Select(reply => new PostReplyModel
            {
                Id = reply.Id,
                AuthorId = reply.User.Id,
                AuthorName = reply.User.UserName,
                AuthorImageUrl = reply.User.ProfileImage,
                AuthorRating = reply.User.Rating,
                Created = reply.Created,
                ReplyContent = reply.Content
            });
        }
    }
}

GoFish.Web/Views/Forum/Detail.cshtml
@model GoFish.Web.Models.Forum.ForumDetailModel

@{
    ViewData["Title"] = "Detail";
}

<h1>Welcome to the @Model.Forum.Title Forum</h1>
@if (Model.Posts.Any())
{
<table class="table table-hover" id="forumIndexTable">
    <tbody>
        @foreach (var post in Model.Posts)
        {
        <tr>
            <td>
                <a asp-controller="Post" asp-action="Index" asp-route-id="@post.Id">
                   @post.Title
                </a>
            </td>
            <td>
                @post.AuthorName
            </td>
            <td>
                @post.DateCreated
            </td>
            <td>
                @post.RepliesCount
            </td>
        </tr>
        }
    </tbody>
</table>
}
else
{
    <div>
        <h3>It looks like there are no @Model.Forum.Title posts yet.</h3>
    </div>
}

GoFish.Web/Views/Forum/Index.cshtml
@model  GoFish.Web.Models.Forum.ForumIndexModel
@{
    ViewData["Title"] = "Index";
}

<h1>Forums</h1>
<table class="table table-hover" id="forumIndexTable">
    <tbody>
        @foreach (var forum in Model.ForumList)
        {
            <tr>
                <td>
                    <a asp-controller="Forum" asp-action="Detail" asp-route-id="@forum.Id">
                        @forum.Title 
                    </a>
                </td>
                <td>
                    @forum.Description
                </td>
            </tr>
        }
    </tbody>
</table>

GoFish.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

GoFish.Web/Views/Post/Index.cshtml
@model GoFish.Web.Models.Post.PostIndexModel
@{
    ViewData["Title"] = "Index";
}

<h1>@Model.Title</h1>

<div>
    Author: @Model.AuthorName (@Model.AuthorRating)<br />
    Created: @Model.Created
</div>

<div>
    @Model.PostContent
</div>

@if (Model.Replies.Any())
{
    foreach (var reply in @Model.Replies)
    {
        <div>
            <div>Reply Author: @reply.AuthorName</div>
            <div>Reply Created: @reply.Created</div>
        </div>
        <div>
            Reply: @reply.ReplyContent
        </div>
    }
}

GoFish.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GoFish.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GoFish Forum</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Forum" asp-action="Index">Forums</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - GoFish.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>